repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8'
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.4.2
        files: \.([jt]sx?|css|json|yml|yaml)$ # *.js, *.jsx, *.ts, *.tsx, *.css, ...
        types: [file]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.12.0'
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@9.12.0
          - '@eslint/eslintrc@3.1.0'
          - '@eslint/js@9.12.0'
          - '@eslint/compat@1.2.0'
          - eslint-config-next@15.0.0-rc.1
          - next@15.0.0-rc.1
          - typescript-eslint@8.9.0
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.8.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: checkstyle-hl7log-extractor
        name: checkstyle (hl7log-extractor)
        language: system
        verbose: true
        pass_filenames: false
        files: \.java$
        entry: bash -c 'cd extractor/hl7log-extractor && ./gradlew checkstyleMain checkstyleTest'
      - id: checkstyle-tests
        name: checkstyle (tests)
        language: system
        verbose: true
        pass_filenames: false
        files: \.java$
        entry: bash -c 'cd tests/ingest && ./gradlew checkstyleMain checkstyleTest'
      - id: checkstyle-keycloak
        name: checkstyle (keycloak)
        language: system
        verbose: true
        pass_filenames: false
        files: \.java$
        entry: bash -c 'cd keycloak/event-listener && ./gradlew clean checkstyleMain checkstyleTest'
