---
# Molecule Integration Test - Converge
# Tests actual k3s installation in a container with systemd
- name: Converge
  hosts: all
  gather_facts: true
  environment: '{{ cluster_k8s_environment }}'

  roles:
    - role: k3s
